### PR TITLE
Fix connecting timeout without returning -1 in ACE_Cached_Connect_Strategy_T

### PR DESCRIPTION
**Pull request by likema**
ACE_Cached_Connect_Strategy_T::cached_connect timeout but still return 0.

### CODE REVIEW

**Comment by jwillemsen** [comment]
Thanks for the pull request, can you extend/add a test under ACE/tests that reproduced this problem?

**Comment by likema** [comment]
OK, I will do it later.

**Comment by likema** [comment]
It is hard to simulate EWOULDBLOCK or ETIMEDOUT. 

```
if (errno == EWOULDBLOCK || errno == ETIMEDOUT)
        {
          errno = ENOTSUP;
          return -1;
        }
```

In man connect,

* *EAGAIN* No  more  free  local  ports  or  insufficient  entries  in  the  routing  cache.   For  AF_INET  see  the description of  /proc/sys/net/ipv4/ip_local_port_range ip(7) for information on how to increase the number of local ports.
* *ETIMEDOUT* Timeout while attempting connection.  The server may be too busy to accept new connections.  Note that for IP sockets the timeout may be very long when syncookies are enabled on the server.

I have written a test with ACE_Synch_Options timeout, but it reports errno is ETIME rather than EAGAIN or ETIMEDOUT.

**Comment by jwillemsen** [comment]
New test also needs to be added to tests/run_test.lst so that it runs as part of the test suite

**Comment by mitza-oci** [comment]
Since the change was reverted, is there a way to reopen the pull request?

**Comment by jwillemsen** [comment]
As far as I remember you have to create a new pull request

**Comment by likema** [comment]
Why revert it?

**Comment by jwillemsen** [comment]
The pull request was reverted through request #143 because the new unit test was failing on most of the platforms.

**Pull request merged**
