### PR TITLE
Fix memory leak by incorrect assignment of Intrusive_Auto_Ptr.

### PR DESCRIPTION
**Pull request by likema**

### CODE REVIEW

**Comment by jwillemsen** [comment]
Please extend or add a new test under ACE/tests that reproduces this issue automatically which we can we use to validate the problem and also that makes sure the issue doesn't get introduced back in the future.

**Comment by likema** [comment]
OK, done.

**Comment by likema** [comment]
Before fixing it, the new test will be crashed. Now, it passed.

**Comment by jwillemsen** [comment]
Thanks, as last request please add some documentation to the class and test to explain the behavior and what the test expects

**Comment by likema** [comment]
Since the class already had straightforward docs, I just added docs for the unit test.

**Comment by jwillemsen** [comment]
Did a local test and reviewed the changes, will merge this, thanks for making the fix and extending the test.

**Pull request merged**
