### PR TITLE
Notify/ProxySupplier: Fix memory leak

### PR DESCRIPTION
**Pull request by jjardon**

### CODE REVIEW

**Comment by jwillemsen** [comment]
In which unit test do you see this memory leak?

**Comment by jjardon** [comment]
Didn't run any test (yet). This is what the code does in orbsvcs/orbsvcs/Notify/ProxyConsumer.cpp for the "auto_supplier", so I though this was changed by mistake in commit 1d73306e756d54c2bbc6b378481358433c3fc18c

**Comment by jwillemsen** [comment]
Could you run the Notification service unit tests and make sure none crash after this change?

**Comment by jjardon** [comment]
Do you mean the ones in TAO/orbsvcs/tests/unit/Notify/MC ?

**Comment by jwillemsen** [comment]
The ones under TAO/orbsvsc/tests/Notify

**Comment by jjardon** [comment]
The

$ ./run_test.pl 

Testing Notification Service with config file = notify.rt.conf ....


Testing ConnectDisconnect....

ACE_ASSERT: file Notify/ProxySupplier.cpp, line 89 assertion failed for 'this->consumer_.get() != 0'.Aborting...
(23893|140305723582272) EXCEPTION, Error: 
system exception, ID 'IDL:omg.org/CORBA/COMM_FAILURE:1.0'
TAO exception, minor code = 6 (failed to recv request response; ENOENT), completed = MAYBE

ERROR: ConnectDisconnect returned 1

**Comment by jjardon** [comment]
The tests actually fails, I will close this pull request for now:

$ ./run_test.pl 

Testing Notification Service with config file = notify.rt.conf ....


Testing ConnectDisconnect....

ACE_ASSERT: file Notify/ProxySupplier.cpp, line 89 assertion failed for 'this->consumer_.get() != 0'.Aborting...
(23893|140305723582272) EXCEPTION, Error: 
system exception, ID 'IDL:omg.org/CORBA/COMM_FAILURE:1.0'
TAO exception, minor code = 6 (failed to recv request response; ENOENT), completed = MAYBE

ERROR: ConnectDisconnect returned 1

**Pull request closed without merging**
