### PR TITLE
feature/aix5.1

### PR DESCRIPTION
**Pull request by likema**
* Lack unsetenv, log2 and pthread_attr_setstack in AIX 5.1
* ssize_t is long  in ppc or ppc64.
* size_t is unsigned long in ppc or ppc64.

### CODE REVIEW

**Comment by jwillemsen** [comment]
Steve, can you check this pull request given the fact that you have some AIX builds?

**Comment by jwillemsen** [comment]
Fuzz seems to fail, so this is impossible to merge and I don't have an AIX box so can't review this

**Comment by shuston** [comment]
I left comments on the changes themselves; this set of changes should not be merged until the problems can be corrected and re-reviewed.

**Comment by likema** [comment]
Done.

Please review it.

**Comment by shuston** [comment]
If the CI build is error-free, I approve merging this.

**Comment by jwillemsen** [comment]
Steve, are the changes ok to merge?

**Pull request merged**
